nodeLinker: node-modules

packageExtensions:
  "@langchain/langgraph-checkpoint-mongodb@*":
    peerDependenciesMeta:
      "@langchain/langgraph-checkpoint":
        optional: true
  "@langchain/langgraph@*":
    peerDependenciesMeta:
      zod:
        optional: true
  "react-native-math-view@*":
    peerDependenciesMeta:
      react-native:
        optional: true
      react-native-svg:
        optional: true
