export const MOCK_QUESTIONS = [
  // MATH - EASY
  {
    text: 'What is 3 + 5?',
    options: ['6', '7', '8', '9'],
    correctIndex: 2,
    subject: 'MATH',
    difficulty: 'EASY',
    explanation: `**Adding 3 + 5**\n\nYou can count on from 3:\n\n3 → 4 → 5 → 6 → 7 → **8**\n\nThat's 5 steps forward, so **3 + 5 = 8**.`,
  },
  {
    text: 'What is 10 - 4?',
    options: ['5', '6', '7', '8'],
    correctIndex: 1,
    subject: 'MATH',
    difficulty: 'EASY',
    explanation: `**Subtracting 4 from 10**\n\nCount backwards from 10 by 4 steps:\n\n10 → 9 → 8 → 7 → **6**\n\nSo **10 − 4 = 6**.`,
  },
  {
    text: 'What is 2 × 6?',
    options: ['10', '12', '14', '16'],
    correctIndex: 1,
    subject: 'MATH',
    difficulty: 'EASY',
    explanation: `**Multiplying 2 × 6**\n\nMultiplication is repeated addition:\n\n2 × 6 = 2 + 2 + 2 + 2 + 2 + 2 = **12**\n\nOr think of it as 6 groups of 2: **12** total.`,
  },
  {
    text: 'How many sides does a triangle have?',
    options: ['2', '3', '4', '5'],
    correctIndex: 1,
    subject: 'MATH',
    difficulty: 'EASY',
    explanation: `**Triangles have 3 sides**\n\nThe word *triangle* comes from Latin: **tri** = three, **angulus** = angle. Every triangle has:\n\n- **3 sides**\n- **3 angles**\n- **3 corners (vertices)**`,
  },

  // MATH - MEDIUM
  {
    text: 'What is 7 × 8?',
    options: ['48', '54', '56', '63'],
    correctIndex: 2,
    subject: 'MATH',
    difficulty: 'MEDIUM',
    explanation: `**7 × 8 = 56**\n\nA helpful trick: **7 × 8 = 56** — notice 5, 6, 7, 8 appear in order!\n\nYou can also break it down:\n- 7 × 8 = 7 × 4 × 2\n- 7 × 4 = 28\n- 28 × 2 = **56**`,
  },
  {
    text: 'What is 144 ÷ 12?',
    options: ['10', '11', '12', '13'],
    correctIndex: 2,
    subject: 'MATH',
    difficulty: 'MEDIUM',
    explanation: `**144 ÷ 12 = 12**\n\nDivision asks: "how many groups of 12 fit into 144?"\n\n12 × 12 = 144, which means 12² = 144.\n\nSo **144 ÷ 12 = 12** — it's also a perfect square!`,
  },
  {
    text: 'What is 25% of 80?',
    options: ['15', '20', '25', '30'],
    correctIndex: 1,
    subject: 'MATH',
    difficulty: 'MEDIUM',
    explanation: `**25% of 80 = 20**\n\n25% means **one quarter (¼)**. To find one quarter:\n\n80 ÷ 4 = **20**\n\nAlternatively: 25% = 0.25, so 0.25 × 80 = **20**.`,
  },
  {
    text: 'How many degrees are in a right angle?',
    options: ['45°', '90°', '180°', '360°'],
    correctIndex: 1,
    subject: 'MATH',
    difficulty: 'MEDIUM',
    explanation: `**A right angle = 90°**\n\nA full rotation is **360°**. Half of that is a straight line at **180°**. Half again gives a **right angle at 90°**.\n\nRight angles are everywhere — the corners of a square, the letter "L", and the corner of a piece of paper.`,
  },

  // SCIENCE - EASY
  {
    text: 'What planet is closest to the Sun?',
    options: ['Venus', 'Mercury', 'Earth', 'Mars'],
    correctIndex: 1,
    subject: 'SCIENCE',
    difficulty: 'EASY',
    explanation: `**Mercury is closest to the Sun**\n\nThe order of planets from the Sun:\n\n1. **Mercury** ← closest\n2. Venus\n3. Earth\n4. Mars\n\nMercury is so close that a year there lasts only **88 Earth days**!`,
  },
  {
    text: 'What gas do plants breathe in?',
    options: ['Oxygen', 'Nitrogen', 'Carbon Dioxide', 'Hydrogen'],
    correctIndex: 2,
    subject: 'SCIENCE',
    difficulty: 'EASY',
    explanation: `**Plants absorb Carbon Dioxide (CO₂)**\n\nDuring **photosynthesis**, plants:\n\n1. Take in **CO₂** from the air\n2. Use **sunlight** as energy\n3. Combine CO₂ with water to make sugar\n4. Release **oxygen** as a by-product\n\nThis is why plants are so important — they produce the oxygen we breathe!`,
  },
  {
    text: 'How many legs does a spider have?',
    options: ['6', '8', '10', '12'],
    correctIndex: 1,
    subject: 'SCIENCE',
    difficulty: 'EASY',
    explanation: `**Spiders have 8 legs**\n\nSpiders belong to a group called **arachnids**, not insects. Here's how to tell them apart:\n\n- **Insects** → 6 legs (e.g., ants, bees)\n- **Arachnids** → **8 legs** (e.g., spiders, scorpions)\n\nAll 8 legs attach to the spider's front body section.`,
  },
  {
    text: 'What is the largest ocean?',
    options: ['Atlantic', 'Indian', 'Arctic', 'Pacific'],
    correctIndex: 3,
    subject: 'SCIENCE',
    difficulty: 'EASY',
    explanation: `**The Pacific Ocean is the largest**\n\nOcean sizes ranked:\n\n1. **Pacific** ← largest (covers more area than all land combined!)\n2. Atlantic\n3. Indian\n4. Arctic\n\nThe Pacific Ocean is so big that all of Earth's continents could fit inside it.`,
  },

  // SCIENCE - MEDIUM
  {
    text: 'What is H₂O commonly known as?',
    options: ['Salt', 'Water', 'Sugar', 'Air'],
    correctIndex: 1,
    subject: 'SCIENCE',
    difficulty: 'MEDIUM',
    explanation: `**H₂O is water**\n\nThe formula tells us exactly what's in water:\n\n- **H₂** = 2 hydrogen atoms\n- **O** = 1 oxygen atom\n\nWhen 2 hydrogen atoms bond with 1 oxygen atom, they form a water molecule. Water is the only substance naturally found as a solid (ice), liquid, and gas (steam) on Earth.`,
  },
  {
    text: 'Which organ pumps blood in the body?',
    options: ['Brain', 'Lungs', 'Heart', 'Liver'],
    correctIndex: 2,
    subject: 'SCIENCE',
    difficulty: 'MEDIUM',
    explanation: `**The heart pumps blood**\n\nYour heart is a muscle about the size of your fist. It works like a pump:\n\n1. Blood enters the **right side** of the heart\n2. Gets sent to the **lungs** to pick up oxygen\n3. Returns to the **left side** of the heart\n4. Gets pumped out to the **whole body**\n\nIt beats around **100,000 times every day** without stopping!`,
  },

  // ENGLISH - EASY
  {
    text: 'What is the plural of "child"?',
    options: ['Childs', 'Children', 'Childes', 'Childern'],
    correctIndex: 1,
    subject: 'ENGLISH',
    difficulty: 'EASY',
    explanation: `**The plural of "child" is "children"**\n\n"Child" is an **irregular noun** — it doesn't follow the normal rule of just adding *-s*.\n\nOther irregular plurals work similarly:\n- man → **men**\n- woman → **women**\n- child → **children**\n\nThese forms come from very old English and must be memorized.`,
  },
  {
    text: 'Which word is a verb?',
    options: ['Happy', 'Running', 'Blue', 'Table'],
    correctIndex: 1,
    subject: 'ENGLISH',
    difficulty: 'EASY',
    explanation: `**"Running" is a verb**\n\nVerbs are **action or doing words**. To check if a word is a verb, ask: *"Can I do this?"*\n\n- Happy → describes a feeling (adjective)\n- **Running** → you can run! ✓ (verb)\n- Blue → describes a colour (adjective)\n- Table → a thing (noun)\n\n*Running* is a **present participle** form of the verb "to run".`,
  },

  // HISTORY - EASY
  {
    text: 'Who was the first president of the USA?',
    options: ['Abraham Lincoln', 'George Washington', 'Thomas Jefferson', 'John Adams'],
    correctIndex: 1,
    subject: 'HISTORY',
    difficulty: 'EASY',
    explanation: `**George Washington was the first president**\n\nGeorge Washington served as the **1st President of the United States** from 1789 to 1797. Before becoming president, he led the American army to victory in the Revolutionary War against Britain.\n\nHe is so respected that his face appears on the **US dollar bill** and the **25-cent coin**.`,
  },
  {
    text: 'What ancient civilization built the pyramids?',
    options: ['Romans', 'Greeks', 'Egyptians', 'Chinese'],
    correctIndex: 2,
    subject: 'HISTORY',
    difficulty: 'EASY',
    explanation: `**The ancient Egyptians built the pyramids**\n\nThe most famous pyramids are at **Giza** in Egypt, built around 2560 BC. They were built as **tombs for pharaohs** (Egyptian kings).\n\nThe Great Pyramid of Giza was the tallest structure in the world for **over 3,800 years**. It was built using around **2.3 million stone blocks**, each weighing up to 80 tonnes!`,
  },

  // GEOGRAPHY - EASY
  {
    text: 'What is the capital of France?',
    options: ['London', 'Berlin', 'Paris', 'Madrid'],
    correctIndex: 2,
    subject: 'GEOGRAPHY',
    difficulty: 'EASY',
    explanation: `**Paris is the capital of France**\n\nParis has been France's capital for over **1,000 years**. It is home to some of the world's most famous landmarks:\n\n- 🗼 The **Eiffel Tower**\n- 🖼️ The **Louvre** museum\n- ⛪ **Notre-Dame** cathedral\n\nWith about 2 million people in the city (12 million in the metro area), it is also one of Europe's largest cities.`,
  },
  {
    text: 'How many continents are there?',
    options: ['5', '6', '7', '8'],
    correctIndex: 2,
    subject: 'GEOGRAPHY',
    difficulty: 'EASY',
    explanation: `**There are 7 continents**\n\nThe seven continents from largest to smallest:\n\n1. **Asia**\n2. **Africa**\n3. **North America**\n4. **South America**\n5. **Antarctica**\n6. **Europe**\n7. **Australia**\n\nSome countries (like Russia and Egypt) are so large they span two continents!`,
  },
  {
    text: 'Which continent is the largest?',
    options: ['Africa', 'Asia', 'Europe', 'North America'],
    correctIndex: 1,
    subject: 'GEOGRAPHY',
    difficulty: 'EASY',
    explanation: `**Asia is the largest continent**\n\nAsia covers about **44.6 million km²** — nearly one third of all the land on Earth. It is home to:\n\n- The **most people** of any continent (~4.7 billion)\n- The **highest point** on Earth: Mount Everest (8,849 m)\n- The **largest country** by area: Russia\n- The **most populous country**: China (and India close behind)`,
  },
  {
    text: 'What is the longest river in the world?',
    options: ['Amazon', 'Nile', 'Mississippi', 'Yangtze'],
    correctIndex: 1,
    subject: 'GEOGRAPHY',
    difficulty: 'EASY',
    explanation: `**The Nile is the longest river**\n\nThe **Nile River** stretches about **6,650 km** through northeastern Africa, flowing through countries including Uganda, Sudan, and Egypt before emptying into the Mediterranean Sea.\n\nThe ancient Egyptian civilization grew along its banks because the Nile flooded every year, leaving behind **rich, fertile soil** perfect for farming.`,
  },
];
